AWSTemplateFormatVersion: "2010-09-09"
Description: Simple S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Value: !Ref MyBucket
